---
title: "Describe data"
format: html
editor: visual
---

1.  Load data and relevant libraries

```{r}
#| message: false
library("tidyverse")
library("dplyr")

```

```{r}
data_dir <- "../data"
data_file <- "/03_data_load.tsv.gz" 
describe_input <- read_tsv(str_c(data_dir, data_file))

```

Here a basic summary of the data is computed. The mean of each experiment has been taken by grouping by gene ID and experiment. The reads, reads per million and reads per kilobase per million are all identical, therefore standard deviation was not calculated. The mean and standard deviation of gene expression was calculated.

```{r}
describe_input |> 
  mutate(experiment = substr(experiment, 1, nchar(experiment) - 2)) |> 
  group_by(gene_ID, experiment) |> 
  summarise(
    mean_reads = mean(mean_reads, na.rm = TRUE),
    mean_rpm = mean(mean_rpm, na.rm = TRUE),
    mean_rpkm = mean(mean_rpkm, na.rm = TRUE),
    mean_gene_expression = mean(gene_expression, na.rm = TRUE),
    sd_gene_expression = sd(gene_expression, na.rm = TRUE),
    .groups = "drop"  # Ensure ungrouped data for ggplot
  ) |> 
  ggplot(aes(x = experiment, y = sd_gene_expression)) +
  geom_boxplot() +  # Create boxplot
  theme_minimal() +
  labs(
    title = "Boxplot of Gene Expression Standard Deviations",
    x = "Experiment",
    y = "Standard Deviation of Gene Expression"
  )
```